version: '3'

services:
  python:
    build: .
    image: python-sng
    volumes:
      - ../spectral_network_generator:/spectral_network_generator
    working_dir: /spectral_network_generator
    command: /bin/bash
    tty: true
